### ISSUE TITLE
怎么配置反代

### ISSUE THREAD

**Issue by xqa** [gptlink/gptlink-deploy#5]
你那个gptlink docker 里面还加了nginx吗，直接暴露80，443。请问怎么配合Nginx Proxy Manager 使用。
我直接暴露端口可以使用，但是把端口隐藏通过npm网络访问就不得行，80，443和9503都不行。就很奇怪
```yml
version: '3.8'

networks:
  backend:
  npm:
    external: true

services:

  ### GPTLINK ################################################
  gptlink:
    image: overnick/gptlink:latest
    container_name: gptlink
    volumes:
      - ${HOME}/volumes/gptlink/logs/server:/app/gptserver/runtime/logs
      - ${HOME}/volumes/gptlink/logs/nginx:/var/log/nginx
    environment:
      - APP_NAME=${GPTLINK_APP_NAME}
      - APP_URL=${GPTLINK_APP_URL}
      - JWT_SECRET=${GPTLINK_JWT_SECRET}
      - ADMIN_USERNAME=${GPTLINK_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${GPTLINK_ADMIN_PASSWORD}
      - DB_HOST=${GPTLINK_DB_HOST:-mysql}
      - DB_PORT=${GPTLINK_DB_PORT:-3306}
      - DB_DATABASE=${GPTLINK_DB_DATABASE}
      - DB_USERNAME=${GPTLINK_DB_USERNAME}
      - DB_PASSWORD=${GPTLINK_DB_PASSWORD}
      - REDIS_HOST=${GPTLINK_REDIS_HOST:-redis}
      - REDIS_AUTH=${GPTLINK_REDIS_AUTH:-(null)}
      - REDIS_PORT=${GPTLINK_REDIS_PORT:-6379}
      - OPENAI_HOST=${OPENAI_HOST:-}
      - OPENAI_PORT=${OPENAI_PORT:-}
      - OPENAI_PROXY_HOST=${OPENAI_PROXY_HOST:-}
      - OPENAI_PROXY_PORT=${OPENAI_PROXY_PORT:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-4000}
      - OPENAI_MAX_RESPONSE_TOKENS=${OPENAI_MAX_RESPONSE_TOKENS:-1000}
    networks:
      - backend
    expose:
      - 9503
    labels:
      - docker-volume-backup.stop-during-backup=true

  ### Redis ################################################
  redis:
    image: redis:alpine
    volumes:
      - ${HOME}/volumes/gptlink/redis:/data
    networks:
      - backend
    labels:
      - docker-volume-backup.stop-during-backup=true

  ### MySQL ################################################
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-gptlink}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${HOME}/volumes/gptlink/mysql:/var/lib/mysql
    networks:
      - backend
    labels:
      - docker-volume-backup.stop-during-backup=true
```
